import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import logo from '../../public/images/logoBlue.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div id='logo' className='relative'>
      <Image src={logo} alt='logo' className='translate-x-360 translate-y-60'></Image>
    </div>
  )
}
