import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import logoBlue from '../../public/images/logoBlue.png'
import logoWhite from '../../public/images/logoWhite.png'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='h-3436 relative'>
      <div className=' overflow-y-auto min-h-screen'>
        {/*헤더 전체 */}
        <div className='h-140'>
          {/*로그인 바 */}
          <div className='h-40'></div>
          {/*네비게이션 바 */}
          <div id='header' className='flex flex-nowrap h-100 gap-108 place-items-center ml-10'>
            {/*로고 이미지*/}
            <Link legacyBehavior href="/">
              <a>
                <Image src={logoBlue} alt="로고" width={200} height={100} />
              </a>
            </Link>
            {/*메뉴 바*/}
            <div id='nav' className='w-1000 h-30px'>
              {/*카테고리들 */}
              <ul className="flex flex-nowrap gap-127 font-['Gsans'] text-19">
                <li> <Link href='/materials'>학습자료</Link> </li>
                <li> <Link href='/freeboard'>자유게시판</Link> </li>
                <li> <Link href='/infoboard'>정보게시판</Link> </li>
                <li> <Link href='/qna'>Q&A</Link> </li>
                <li> <Link href='/mypage'>마이페이지</Link> </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      {/*하단 바*/}
      <div className='w-full h-216 absolute bottom-0 bg-grey'>
        <Image src={logoWhite} alt='logo'></Image> 
      </div>
    </div>
  )
}
